### ISSUE TITLE
Always use `settings.json`

### ISSUE THREAD

**Issue by kamre** [ehnat0n/aqw-opcua-server#5]
Currently it is required to pass path to `settings.json` file as argument. But the server can't work properly without it.

So lets always use this `settings.json` file and assume that it is in the same directory where server executable is located like this:
```
aqw-opcua-server
└─build
  └─bin
    └─Release
      ├─aqw-opcua-server.exe
      └─settings.json
```
* We can use `set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ...)` to change where executable will be placed.
* Copying `settings.json` can be done via `file(GENERATE ...)`, this file should be copied for each configuration in separate folder (`bin/Release`, `bin/Debug`, ...).
* Path to executable can be extracted from `argv[0]` in `main` and used for constructing full path to `settings.json` that will be loaded.
* Server should not start without `settings.json` and print error message if the file is not available.
* Can also rename `settings_example.json` back to `settings.json` and change `.gitignore` back because it is expected that developers will only edit `settings.json` inside `build/bin` directory.
* Update `Readme.md` section about using `settings.json`

**Comment by digumnov** [comment]
Resolved with latest update. Feature added.
