### ISSUE TITLE
Replace tabs with spaces

### ISSUE THREAD

**Issue by kamre** [ehnat0n/aqw-opcua-server#6]
Tabs are used in the code for indentation and sometimes they are mixed with spaces for indentation. In general using specific number of spaces for block indentation is better practice so lets change all tabs to spaces.

Also its worth to remove trailing spaces as they are simply redundant. Can use [this MSVC extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer) for making the change.

**Comment by digumnov** [comment]
Went through all the files and "untabified" them. Some indents maybe incorrect, but I'll fix them in the process. All the current tabs were converted to spaces though. And I turned on the option to fill tabs with spaces. Should be OK from now on.

You can check the latest commit.

**Comment by kamre** [comment]
Better create new branch for any changes and merge with master via pull request instead of pushing directly to master.

**Comment by digumnov** [comment]
Here is the link as per our conversation: https://github.com/ehnat0n/aqw-opcua-server/commit/15bc2488930b5b7a001b10949effc4fe6bd336d8
Agree with the branch/pull request procedure. Just realized when it was too late. Probably not worth the time rolling back and recreating now.
